apiVersion: v1
kind: BuildConfig
metadata:
    labels:
        app: chiaretto-tam-pipeline
    name: chiaretto-tam-pipeline
spec:
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    source:
        git:
            ref: master
            uri: https://github.com/lgchiaretto/tam-chiaretto.git
    strategy:
        jenkinsPipelineStrategy:
            jenkinsfilePath: openshift/pipelines/Jenkinsfile
        type: JenkinsPipeline
    triggers:
        - github:
            secret: secret
          type: GitHub
        - generic:
            secret: secret
          type: Generic
        - bitbucket:
            secret: secret
          type: Bitbucket
