pipeline {
    agent {
        node {label 'python'}
    }
    environment {
        APPLICATION_NAME = 'python-nginx'
        GIT_REPO="http://github.com/lgchiaretto/tam-chiaretto.git"
        GIT_BRANCH="master"
        STAGING_TAG = "promoteToStaging"
        PROD_TAG = "promoteToProduction"
        STAGING_PROJECT = "staging"
        PROD_PROJECT = "production"
        TEMPLATE_NAME = "python-nginx"
        ARTIFACT_FOLDER = "target"
        PORT = 8081;
    }
    stages {
        stage('Get Latest Code') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
            }
        }
        stage ("Install Dependencies") {
            steps {
                sh """
                pip install virtualenv
                virtualenv --no-site-packages .
                source bin/activate
                pip install -r app/requirements.pip
                deactivate
                """
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                source bin/activate
                nosetests app --with-xunit
                deactivate
                '''
                junit "nosetests.xml"
            }
        }
        stage('Store Artifact'){
            steps{
                script{
                    def safeBuildName  = "${APPLICATION_NAME}_${BUILD_NUMBER}",
                        artifactFolder = "${ARTIFACT_FOLDER}",
                        fullFileName   = "${safeBuildName}.tar.gz",
                        applicationZip = "${artifactFolder}/${fullFileName}"
                        applicationDir = ["app",
                                            "config",
                                            "Dockerfile",
                                            ].join(" ");
                    def needTargetPath = !fileExists("${artifactFolder}")
                    if (needTargetPath) {
                        sh "mkdir ${artifactFolder}"
                    }
                    sh "tar -czvf ${applicationZip} ${applicationDir}"
                    archiveArtifacts artifacts: "${applicationZip}", excludes: null, onlyIfSuccessful: true
                }
            }
        }
        stage('Create Image Builder Staging') {
            when {
                expression {
                    openshift.withCluster() {
                        openshift.withProject(STAGING_PROJECT) {
                            return !openshift.selector("bc", "${TEMPLATE_NAME}").exists();
                        }
                }
            }
        }
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject(STAGING_PROJECT) {
                        openshift.newBuild("--name=${TEMPLATE_NAME}", "--docker-image=docker.io/nginx:mainline-alpine", "--binary=true")
                        }
                    }
                }
            }
        }
        stage('Create Image Builder Production') {
            when {
                expression {
                    openshift.withCluster() {
                        openshift.withProject(PROD_PROJECT) {
                            return !openshift.selector("bc", "${TEMPLATE_NAME}").exists();
                        }
                }
            }
        }
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject(PROD_PROJECT) {
                        openshift.newBuild("--name=${TEMPLATE_NAME}", "--docker-image=docker.io/nginx:mainline-alpine", "--binary=true")
                        }
                    }
                }
            }
        }
        stage('Build Image on Staging') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(env.STAGING_PROJECT) {
                            openshift.selector("bc", "$TEMPLATE_NAME").startBuild("--from-archive=${ARTIFACT_FOLDER}/${APPLICATION_NAME}_${BUILD_NUMBER}.tar.gz", "--wait=true")
                        }
                    }
                }
            }
        }
        stage('Build Image on Production') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(env.PROD_PROJECT) {
                            openshift.selector("bc", "$TEMPLATE_NAME").startBuild("--from-archive=${ARTIFACT_FOLDER}/${APPLICATION_NAME}_${BUILD_NUMBER}.tar.gz", "--wait=true")
                        }
                    }
                }
            }
        }
        stage('Promote to STAGING?') {
            steps {
                timeout(time:15, unit:'MINUTES') {
                    input message: "Promote to STAGING?", ok: "Promote"
                }
                script {
                    openshift.withCluster() {
                        openshift.tag("${STAGING_PROJECT}/${TEMPLATE_NAME}:latest", "${STAGING_PROJECT}/${TEMPLATE_NAME}:${STAGING_TAG}")
                    }
                }
            }
        }
        stage('Rollout to STAGING') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(STAGING_PROJECT) {
                            if (openshift.selector('dc', '${TEMPLATE_NAME}').exists()) {
                                openshift.selector('dc', '${TEMPLATE_NAME}').delete()
                                openshift.selector('svc', '${TEMPLATE_NAME}').delete()
                                openshift.selector('route', '${TEMPLATE_NAME}').delete()
                            }
                        openshift.newApp("${TEMPLATE_NAME}:${STAGING_TAG}").narrow("svc").expose("--port=${PORT}")
                        }
                    }
                } 
            }
        }
        stage('Promote to PRODUCTION?') {
            steps {
                timeout(time:15, unit:'MINUTES') {
                    input message: "Promote to PRODUCTION?", ok: "Promote"
                }
                script {
                    openshift.withCluster() {
                        openshift.tag("${PROD_PROJECT}/${TEMPLATE_NAME}:latest", "${PROD_PROJECT}/${TEMPLATE_NAME}:${PROD_TAG}")
                    }
                }
            }
        }
        stage('Rollout to PRODUCTION') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(PROD_PROJECT) {
                            if (openshift.selector('dc', '${TEMPLATE_NAME}').exists()) {
                                openshift.selector('dc', '${TEMPLATE_NAME}').delete()
                                openshift.selector('svc', '${TEMPLATE_NAME}').delete()
                                openshift.selector('route', '${TEMPLATE_NAME}').delete()
                            }
                        openshift.newApp("${TEMPLATE_NAME}:${PROD_TAG}").narrow("svc").expose("--port=${PORT}")
                        }
                    }
                } 
            }
        }
    }
}
